### ISSUE TITLE
Sublime Text 3 on OSX

### ISSUE THREAD

**Issue by meowsus** [Neway6655/Sublime-Pomodoro#5]
I can't seem to get the keybinding to trigger in ST3, Build 3083, in OSX. Is this plugin only for ST2?

**Comment by Neway6655** [comment]
yeah, i found that this is because mac has defined the 'option + shift' key bindings to input some special characters. 

Here is the same question asked in stackoverflow: http://stackoverflow.com/questions/11876485/how-to-disable-typing-special-characters-when-pressing-option-key-in-mac-os-x

So, alternatively, you can modify the key bindings using the tools mentioned in the link above, or modify the key bindings in sublime, by using another un-conflicted shortcut, e.g. "ctrl+shift+p"

**Comment by Neway6655** [comment]
hi meowsus,

have you tried the method mentioned above? if it can help you, then i will close this issue since it is not an issue for the plugin.

**Comment by meowsus** [comment]
Worked for me! Thanks!

**Comment by Neway6655** [comment]
Close it.
